---
# tasks/main.yml
- name: Instalar apache
  apt:
    name: apache2
    state: present
    update_cache: yes
  notify: Reiniciar Apache 

- name: Iniciar y habilitar apache
  service:
    name: apache2
    state: started
    enabled: yes

