---
- name: Desplegar MySQL en el servidor
  hosts: vm_prueba # grupo a cual se va a aplicar este Playbook
  become: yes # permisos de sudo
  vars_files:
    - secret_vars.yml # Archivo con datos sensibles (nombre de usuario y contraseña)
  tasks:
    - name: Instalar dependencias de MySQL
      apt:
        name: python3-mysqldb
        state: present

    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Asegurarse de que MySQL este en ejecucion
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Crear un nuevo usuario de MySQL
      mysql_user:
        name: "{{ mysql_user_name }}"
        password: "{{ mysql_user_password }}"
        host: '%'
        priv: '*.*:ALL'
        state: present


    - name: Crear base de datos
      mysql_db:
         name: mi_base_de_datos
         state: present

