---
- name: Ejecutar tareas condicionales segun el sistema operativo
  hosts: vm_prueba
  become: yes 
  tasks:
    - name: Instalar curl solo en ubuntu
      apt:
        name: curl
        state: present
      when: ansible_distribution == "Ubuntu"
